# docker/Dockerfile.lambda
FROM public.ecr.aws/lambda/python:3.9

# Copy only lambda requirements
COPY requirements/lambda.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY app/lambda/ ${LAMBDA_TASK_ROOT}/app/lambda/
COPY app/utils/ ${LAMBDA_TASK_ROOT}/app/utils/
COPY app/model.cbm ${LAMBDA_TASK_ROOT}/app/model.cbm

CMD [ "app.lambda.lambda_function.main" ]